// worker-plugins/templates/simple-api-with-react-frontend/frontend/src/App.tsx
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'

import { api } from './api'
import type { Todo } from './api'

export const App = () => {
  const [todos, setTodos] = useState<Todo[]>([])
  const [text, setText] = useState('')
  // 最初の一覧が届くまでは追加させない。後から届いた一覧が、追加した項目を上書きするため。
  const [busy, setBusy] = useState(true)
  const [error, setError] = useState<string>()

  const run = async (action: () => Promise<void>) => {
    setError(undefined)
    try {
      await action()
      return true
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
      return false
    }
  }

  useEffect(() => {
    void run(async () => setTodos(await api.list())).then(() => setBusy(false))
  }, [])

  // 入力欄は送る前に空ける。待つ間に打った文字を、応答で消さないため。
  const add = async (event: FormEvent) => {
    event.preventDefault()
    if (busy) return
    const value = text
    setBusy(true)
    setText('')
    const ok = await run(async () => {
      const todo = await api.add(value)
      setTodos((todos) => [...todos, todo])
    })
    if (!ok) setText((current) => current || value)
    setBusy(false)
  }

  const remove = (id: number) =>
    void run(async () => {
      await api.remove(id)
      setTodos((todos) => todos.filter((todo) => todo.id !== id))
    })

  return (
    <main>
      <h1>ToDo</h1>

      <form onSubmit={(event) => void add(event)}>
        <input
          value={text}
          onChange={(event) => setText(event.target.value)}
          placeholder="やること"
          maxLength={200}
          required
        />
        <button type="submit" disabled={busy}>
          追加
        </button>
      </form>

      {error && <p role="alert">{error}</p>}

      <ul>
        {todos.map((todo) => (
          <li key={todo.id}>
            <span>{todo.text}</span>
            <button type="button" onClick={() => remove(todo.id)}>
              削除
            </button>
          </li>
        ))}
      </ul>
    </main>
  )
}

// worker-plugins/templates/simple-api-with-vue-frontend/frontend/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'

import { api } from './api'
import type { Todo } from './api'

const todos = ref<Todo[]>([])
const text = ref('')
// 最初の一覧が届くまでは追加させない。後から届いた一覧が、追加した項目を上書きするため。
const busy = ref(true)
const error = ref<string>()

const run = async (action: () => Promise<void>) => {
  error.value = undefined
  try {
    await action()
    return true
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e)
    return false
  }
}

onMounted(async () => {
  await run(async () => {
    todos.value = await api.list()
  })
  busy.value = false
})

// 入力欄は送る前に空ける。待つ間に打った文字を、応答で消さないため。
const add = async () => {
  if (busy.value) return
  const value = text.value
  busy.value = true
  text.value = ''
  const ok = await run(async () => {
    todos.value.push(await api.add(value))
  })
  if (!ok) text.value ||= value
  busy.value = false
}

const remove = (id: number) =>
  run(async () => {
    await api.remove(id)
    todos.value = todos.value.filter((todo) => todo.id !== id)
  })
</script>

<template>
  <main>
    <h1>ToDo</h1>

    <form @submit.prevent="add">
      <input v-model="text" placeholder="やること" maxlength="200" required />
      <button type="submit" :disabled="busy">追加</button>
    </form>

    <p v-if="error" role="alert">{{ error }}</p>

    <ul>
      <li v-for="todo in todos" :key="todo.id">
        <span>{{ todo.text }}</span>
        <button type="button" @click="remove(todo.id)">削除</button>
      </li>
    </ul>
  </main>
</template>
